#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  bi-sandbox:
    image: digitalasset/bond-issuance-sandbox:0.0.1
    build:
      context: .
      dockerfile: sandbox.Dockerfile
    ports:
      - "127.0.0.1:6865:6865"
      - "127.0.0.1:7500:7500"
      - "127.0.0.1:7575:7575"
    restart: always
  bi-triggers:
    image: digitalasset/bond-issuance-triggers:0.0.1
    build:
      context: .
      dockerfile: triggers.Dockerfile
    depends_on:
      - "bi-sandbox"
    environment:
      - SANDBOX_HOST=bi-sandbox
      - SANDBOX_PORT=6865
  bi-ui:
    image: digitalasset/bond-issuance-ui:0.0.1
    build:
      context: .
      dockerfile: ui.Dockerfile
    depends_on:
      - "bi-sandbox"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - JSON_API=bi-sandbox
